name: Itsyhome
options:
  bundleIdPrefix: com.nickustinov
  knownRegions: [en, es, fr, de, ru, ja, zh-Hans, zh-Hant, ko, pt-BR, it, pl, Base]
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  LiveKitWebRTC:
    url: https://github.com/livekit/webrtc-xcframework.git
    exactVersion: "137.7151.12"

settings:
  base:
    SWIFT_EMIT_LOC_STRINGS: "YES"
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: R892A93W42
  configs:
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

targets:
  # Main macOS Catalyst app
  Itsyhome:
    type: application
    platform: iOS
    supportedDestinations: [iOS, maccatalyst]
    sources:
      - path: Itsyhome/iOS
      - path: Itsyhome/Shared
      - path: Itsyhome/HomeAssistant
      - path: Itsyhome/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsyhome
        PRODUCT_NAME: Itsyhome
        INFOPLIST_FILE: Itsyhome/Info.plist
        CODE_SIGN_ENTITLEMENTS: Itsyhome/Itsyhome.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_MAC_ICON_IN_CATALYST_APP: YES
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        TARGETED_DEVICE_FAMILY: "6"
        # App metadata
        MARKETING_VERSION: "2.1.0"
        CURRENT_PROJECT_VERSION: "230"
        INFOPLIST_KEY_CFBundleDisplayName: Itsyhome
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
    scheme:
      gatherCoverageData: false
      storeKitConfiguration: Itsyhome/ItsyhomeProducts.storekit
      testTargets:
        - macOSBridgeTests
    entitlements:
      path: Itsyhome/Itsyhome.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.developer.homekit: true
        com.apple.developer.ubiquity-kvstore-identifier: "$(TeamIdentifierPrefix)$(CFBundleIdentifier)"
        com.apple.security.network.client: true
        com.apple.security.network.server: true
    dependencies:
      - target: macOSBridge
        platformFilter: maccatalyst
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins
      - sdk: HomeKit.framework
        embed: false
      - package: LiveKitWebRTC

  # macOS plugin bundle for menu bar
  macOSBridge:
    type: bundle
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsyhome.macOSBridge
        PRODUCT_NAME: macOSBridge
        INFOPLIST_FILE: macOSBridge/Info.plist
        SKIP_INSTALL: YES
        COMBINE_HIDPI_IMAGES: YES
        MACOSX_DEPLOYMENT_TARGET: "14.0"
    sources:
      - path: macOSBridge
        excludes:
          - "Resources/PhosphorIcons/**"
      - path: Itsyhome/Shared
        buildPhase: sources
      - path: Itsyhome/HomeAssistant
        buildPhase: sources
      - path: macOSBridge/Resources/PhosphorIcons
        buildPhase: resources
        type: folder
      - path: macOSBridge/Resources/SecurityIcons
        buildPhase: resources
        type: folder

  # Unit tests for macOSBridge
  macOSBridgeTests:
    type: bundle.unit-test
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsyhome.macOSBridgeTests
        PRODUCT_NAME: macOSBridgeTests
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: macOSBridgeTests
      - path: macOSBridge
        excludes:
          - "MacOSController.swift"
          - "MacOSController+*.swift"
          - "MenuBuilder.swift"
          - "DebugMockAccessories.swift"
          - "HotkeyManager.swift"
          - "CameraPanelManager.swift"
          - "Settings/**"
          - "Controls/ShortcutButton.swift"
          - "PinnedAccessory/**"
      - path: macOSBridge/Settings/PreferencesManager.swift
      - path: macOSBridge/Settings/PreferencesManager+Favourites.swift
      - path: macOSBridge/Settings/PreferencesManager+Hidden.swift
      - path: macOSBridge/Settings/PreferencesManager+Pinned.swift
      - path: macOSBridge/Settings/PreferencesManager+Ordering.swift
      - path: macOSBridge/Settings/PreferencesManager+Cameras.swift
      - path: macOSBridge/Settings/PreferencesManager+Groups.swift
      - path: macOSBridge/Settings/PreferencesManager+Shortcuts.swift
      - path: macOSBridge/Settings/PreferencesManager+Icons.swift
      - path: Itsyhome/Shared
        buildPhase: sources
      - path: Itsyhome/HomeAssistant
        buildPhase: sources
    dependencies:
      - target: macOSBridge
