name: Itsyhome
options:
  bundleIdPrefix: com.nickustinov
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: R892A93W42

targets:
  # Main macOS Catalyst app
  Itsyhome:
    type: application
    platform: iOS
    supportedDestinations: [iOS, maccatalyst]
    sources:
      - path: Itsyhome/iOS
      - path: Itsyhome/Shared
      - path: Itsyhome/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsyhome
        PRODUCT_NAME: Itsyhome
        INFOPLIST_FILE: Itsyhome/Info.plist
        CODE_SIGN_ENTITLEMENTS: Itsyhome/Itsyhome.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_MAC_ICON_IN_CATALYST_APP: YES
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        TARGETED_DEVICE_FAMILY: "6"
        # App metadata
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "110"
        INFOPLIST_KEY_CFBundleDisplayName: Itsyhome
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
    scheme:
      gatherCoverageData: false
      storeKitConfiguration: Itsyhome/ItsyhomeProducts.storekit
    entitlements:
      path: Itsyhome/Itsyhome.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.developer.homekit: true
    dependencies:
      - target: macOSBridge
        platformFilter: maccatalyst
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins
      - sdk: HomeKit.framework
        embed: false

  # macOS plugin bundle for menu bar
  macOSBridge:
    type: bundle
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsyhome.macOSBridge
        PRODUCT_NAME: macOSBridge
        INFOPLIST_FILE: macOSBridge/Info.plist
        SKIP_INSTALL: YES
        COMBINE_HIDPI_IMAGES: YES
        MACOSX_DEPLOYMENT_TARGET: "14.0"
    sources:
      - path: macOSBridge
      - path: Itsyhome/Shared
        buildPhase: sources

  # Unit tests for macOSBridge
  macOSBridgeTests:
    type: bundle.unit-test
    platform: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsyhome.macOSBridgeTests
        PRODUCT_NAME: macOSBridgeTests
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: macOSBridgeTests
      - path: macOSBridge
        excludes:
          - "MacOSController.swift"
          - "MenuBuilder.swift"
          - "HotkeyManager.swift"
          - "Settings/**"
          - "Controls/ShortcutButton.swift"
      - path: Itsyhome/Shared
        buildPhase: sources
    dependencies:
      - target: macOSBridge
